---

- name: Install Gitlab repository
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash

- name: Install GitLab Runner
  apt:
    name: gitlab-ci-multi-runner
    state: present
