---
- name: Add GitLab apt key
  apt_key:
    url: https://packages.gitlab.com/gpg.key
    state: present

- name: Install GitLab Runner dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - debian-archive-keyring
    - apt-transport-https

- name: Add GitLab Runner apt repo
  apt_repository:
    repo: 'deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_major_version }} main'
    state: present

- name: Install GitLab Runner
  apt:
    name: gitlab-ci-multi-runner
    state: latest
    update_cache: yes
