---

- name: (RedHat) Get Gitlab repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/{{ gitlab_runner_package_name }}/script.rpm.sh"
    dest: /tmp/gitlab-runner.script.rpm.sh
    mode: 0744

- name: (RedHat) Install Gitlab repository
  command: bash /tmp/gitlab-runner.script.rpm.sh
  args:
    creates: "/etc/yum.repos.d/runner_{{ gitlab_runner_package_name }}.repo"
  become: true

- name: (RedHat) Update gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}-{{ gitlab_runner_package_version }}"
    gitlab_runner_package_state: "present"
  when: gitlab_runner_package_version is defined

- name: (RedHat) Set gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}"
    gitlab_runner_package_state: "latest"
  when: gitlab_runner_package_version is not defined

- name: (RedHat) Install GitLab Runner
  package:
    name: "{{ gitlab_runner_package }}"
    state: "{{ gitlab_runner_package_state }}"
