---
- name: (Container) Install Gitlab Runner
  import_tasks: install-container.yml
  when: gitlab_runner_container_install

- name: (Container) Delete runners which were removed in GitLab
  docker_container:
    name: "{{ gitlab_runner_container_name }}-check"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    command: verify --delete
    mounts:
      - type: bind
        source: "{{ gitlab_runner_container_mount_path }}"
        target: /etc/gitlab-runner
    cleanup: true
    interactive: true
    tty: true
    detach: false
  register: verified_runners
  changed_when: '"Updated " in verified_runners.container.Output'
  check_mode: false

- import_tasks: list-configured-runners-container.yml

- name: (Container) Register GitLab Runner
  include_tasks: register-runner-container.yml
  vars:
    actual_gitlab_runner_name: "{{ gitlab_runner.name | default(ansible_hostname + '-' + gitlab_runner_index | string) }}"
  when: gitlab_runner.token is defined or gitlab_runner_registration_token | string | length > 0
  loop: "{{ gitlab_runner_runners }}"
  loop_control:
    index_var: gitlab_runner_index
    loop_var: gitlab_runner

- name: Unregister runners which are not longer configured
  include_tasks: unregister-runner-if-not-longer-configured.yml
  when: gitlab_unregister_runner_executors_which_are_not_longer_configured

- name: (Container) Set global options
  import_tasks: global-setup.yml

- name: (Container) Configure GitLab Runner
  include_tasks: config-runners-container.yml
  when: gitlab_runner_config_update_mode == 'by_config_toml'

- name: (Container) Start the container
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    restart_policy: "{{ gitlab_runner_container_restart_policy }}"
    mounts:
      - type: bind
        source: "{{ gitlab_runner_container_mount_path }}"
        target: /etc/gitlab-runner
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: "{{ gitlab_runner_container_network }}"
