- name: Install GitLab Runner (Debian)
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install GitLab Runner (macOS)
  import_tasks: install-macos.yml
  when: ansible_os_family == 'Darwin'

- name: Install GitLab Runner (Arch)
  import_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: (Unix) Delete runners which were removed in GitLab
  command: "{{ gitlab_runner_executable }} verify --delete"
  register: verified_runners
  changed_when: '"Updated " in verified_runners.stderr'
  check_mode: no
  become: "{{ gitlab_runner_system_mode }}"

- name: (Unix) Register GitLab Runner
  include_tasks: register-runner.yml
  when: gitlab_runner.token is defined or gitlab_runner_registration_token | string | length > 0
  loop: "{{ gitlab_runner_runners }}"
  loop_control:
    index_var: gitlab_runner_index
    loop_var: gitlab_runner

- name: Set global options (macOS/Debian/RedHat)
  import_tasks: global-setup.yml

- name: (Unix) Configure GitLab Runner
  include_tasks: config-runners.yml
  when: gitlab_runner_config_update_mode == 'by_config_toml'
