---
- name: Install GitLab Runner (Debian)
  include: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (RedHat)
  include: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Set global options
  include: global-setup.yml

- name: Register GitLab Runner
  include: register-runner.yml
  when: gitlab_runner_registration_token != ''
