---
- include_tasks: line-config-runner-windows.yml
  vars:
    line_name_prefix: "{{ sect_name_prefix }} line:[{{ (line_index|int) + 1 }}/{{ gitlab_runner.extra_configs[section]|list|length }}]: "
  loop: "{{ gitlab_runner.extra_configs[section] | list }}"
  loop_control:
    loop_var: line
    index_var: line_index
