---
- name: (Container) Unregister runner
  community.docker.docker_container:
    name: "{{ gitlab_runner_container_name }}-list"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    command: unregister --name {{ actual_gitlab_runner_name }}'
    mounts:
      - type: bind
        source: "{{ gitlab_runner_container_mount_path }}"
        target: /etc/gitlab-runner
    cleanup: true
    interactive: true
    tty: true
    detach: false
  changed_when: false
  check_mode: false
  when:
    - gitlab_install_target_platform == 'container'

- name: (Windows) Unregister runner
  ansible.windows.win_command: "{{ gitlab_runner_executable }} unregister --name {{ actual_gitlab_runner_name }}"
  args:
    chdir: "{{ gitlab_runner_config_file_location }}"
  when:
    - gitlab_install_target_platform == 'windows'

- name: Unregister runner
  ansible.builtin.command: "{{ gitlab_runner_executable }} unregister --name {{ actual_gitlab_runner_name }}"
  changed_when: true
  when:
    - gitlab_install_target_platform == 'unix'
